### ISSUE TITLE
Handling of default values in function arguments

### ISSUE THREAD

**Issue by janjaapbos** [AlecAivazis/nautilus#44]
I noticed that in Nautilus empty dicts are assigned as default values in function headers. This should not be done, unless you really want to have the mutated dict passed around and reused uninitialised in subsequent calls of that function. The same goes for default list values.

See http://effbot.org/zone/default-values.htm

**Comment by AlecAivazis** [comment]
Thanks for the link - I was aware of the issue and had meant to deal with it before any one else saw it. Guess you caught me. I fixed it in [e94afb](https://github.com/AlecAivazis/nautilus/commit/e94afbec63542462fb9583e6e0f5bb875fe8563a)
