### ISSUE TITLE
Render React Components for Universal Apps

### ISSUE THREAD

**Issue by AlecAivazis** [AlecAivazis/nautilus#6]

**Comment by montemishkin** [comment]
not entirely sure if this is what this issue is about, but just guessing, i figured this might be something you're looking for? 

https://github.com/mjackson/react-stdio

**Comment by montemishkin** [comment]
or at least something along those lines that you could easily whip up yourself

**Comment by aaivazis** [comment]
Yea it shouldn't be too hard to wrap that in a service

**Comment by aaivazis** [comment]
the question is how to add the functionality in a DRY way, I hadn't done much thinking on this (bigger fish to fry) but immediately I'm wondering if its a full blown service so we can impose that it doesn't manage data or is it just a view that we provide?
