### ISSUE TITLE
extra missing packages (Ubuntu 16.04)

### ISSUE THREAD

**Issue by greatsquidkite** [AlecAivazis/nautilus#86]
(before installing nautilus):
> sudo apt-get install libffi-dev

(must be installed before graphene); if not installed before graphene, graphenelib must pip installed:
> sudo apt-get install libssl-dev

**Comment by AlecAivazis** [comment]
awesome! thanks - i'll add those two packages to the docs

**Comment by greatsquidkite** [comment]
Also, the docker commands need to be run as root user

**Comment by AlecAivazis** [comment]
ah, that's an issue with docker in general - if you add your current user to the docker group then you should be good to go
